### ISSUE TITLE
push both v2.0.0 and latest based on 2.0.0 with the CI

### ISSUE THREAD

**Issue by danduk82** [camptocamp/docker-swisstopo-light-basemap#2]
Hi @sbrunner  `v2.0.0` is the current version, and in a docker phylosophy it should be also pushed as `latest`

Is there a way to push both tag `v2.0.0` and `latest` with c2cciutils?

I now map `master` on `unstable`

**Comment by sbrunner** [comment]
For that, you should have a SECURITY.md file, and the last line will be considered as the latest version :-)

**Comment by danduk82** [comment]
fixed with https://github.com/camptocamp/docker-swisstopo-light-basemap/commit/9889c8cb8839d414434e2380e4bbdf40b58f6109
